<div id="icon-lists">
    <style>
        #icon-lists li{display: inline-block;padding: 0 20px 20px 0;}
    </style>
    <ul></ul>
</div>
<script type="text/javascript">
    requirejs(['jquery'], function( $ ) {
        var target = $('#icon-lists ul');
        var from = '001';
        var to = '999';
        var style = '<style>'
        for(var i=600;i<=864;i++){
            var e = 'e';
            if(i<10) e+='00'+i;
            else if(i<100) e+='0'+i;
            else e+=i;
            target.append('<li class='+e+'/>');
            style += "#icon-lists li." +
                e +
                ":before{font-family: 'luma-icons';content:'\\" +
                e +
                "';font-size: 20px;color:#000;}";
        }
        style += '</style>';
        target.append(style);
    });
</script>