<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form">
    <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_product) ?>" method="post"
          data-product-id="<?php echo $_product->getId(); ?>"
          id="product_addtocart_form<?php echo $_product->getId(); ?>"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <?php echo $block->getBlockHtml('formkey')?>
        <div class="bundle-options-container">
            <?php echo $this->getLayout()->createBlock('Ey\Wholesale\Block\Product\View\Type\Bundle')
                ->setTemplate("Ey_Wholesale::product/view/type/bundle/options.phtml")->toHtml(); ?>
            <?php echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View')
                ->setTemplate("Ey_Wholesale::product/view/summary.phtml")->toHtml(); ?>
        </div>
    </form>
</div>
<script>
    require([
        'jquery',
        'Magento_Catalog/js/price-box'
    ], function($){
        var priceBoxes = $('#product_addtocart_form<?php echo $_product->getId(); ?> [data-role=priceBox]');

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
    });
</script>
