<?php /** @var \Amasty\Storelocator\Block\Location $block */ ?>
<?php
$locations = $block->getLocations();

$currentDate = $block->timezoneInterface->date();
$currentDay = $block->timezoneInterface->convertConfigTimeToUtc($currentDate, 'N');
$dayNames = $block->dataHelper->getDaysNames();
$i = 1;
?>
<div id="amlocator_left">
    <?php foreach ($locations as $location) : ?>
        <span name="leftLocation" data-amid="<?= $i ?>">
                <div class="location_header"><?= $this->escapeHtml($location->getName()); ?></div>
            <?= __('Address') ?>: <?= $this->escapeHtml($location->getAddress()); ?>
            <br/>
            <?php if ($this->escapeHtml($location->getState())) : ?>
                <?= __('State') ?>: <?= $this->escapeHtml($location->getState()); ?>
                <br/>
            <?php endif; ?>
            <?= $this->escapeHtml($location->getCity()); ?>
            , <?= $this->escapeHtml($location->getZip()); ?>

            <?php if ($this->getShowAttributes()) : ?>
                <?php if (trim($location->getPhone())) : ?>
                    <br/>
                    <?= __('Phone') ?>: <?= $this->escapeHtml($location->getPhone()); ?>
                <?php endif; ?>
                <?php if (trim($location->getEmail())) : ?>
                    <br/>
                    <?= __('E-mail') ?>: <?= $this->escapeHtml($location->getEmail()); ?>
                <?php endif; ?>
                <?php if (trim($location->getWebsite())) : ?>
                    <br/>
                    <?= __('URL') ?>: <?= $this->escapeHtml($location->getWebsite()); ?>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($location->getScheduleArray() != false) :
                $schedule = $location->getScheduleArray();
                ?>

                <div class="today_schedule">
                        <?= __('Work Time Today:')?>
                    <span>
                            <?= $schedule[$currentDay]['from'][0] ?>:<?= $schedule[$currentDay]['from'][1] ?>
                        -
                        <?= $schedule[$currentDay]['to'][0] ?>:<?= $schedule[$currentDay]['to'][1] ?>
                        <div class="locator_arrow"></div>
                        </span>

                    </div>

                <div class="all_schedule" id="schedule<?= $i ?>">
                    <?php
                    $scheduleDay = 1;

                    foreach ($schedule as $key => $item) {
                        ?>
                        <div>
                            <?= __($dayNames[$key]); ?>:
                            <span>
                                <?= $item['from'][0] ?>:<?= $item['from'][1] ?>
                                -
                                <?= $item['to'][0] ?>:<?= $item['to'][1] ?>
                            </span>
                        </div>
                        <?php
                        $scheduleDay++;
                    }
                    ?>
                </div>
            <?php endif; ?>
            </span>
        <?php $i++ ?>
    <?php endforeach; ?>
</div>