<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Ey\ConfigurableBundle\Block\Catalog\Product\View\Type\Bundle\Option\Configurable */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>

<div class="configurable-bundle field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <label class="label">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <div class="bundle-option-holder configurable-bundle-option-holder">
                <?php foreach ($_selections as $_selection): ?>
                    <input type="hidden"
                           class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                           name="configurable_bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                           value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>" />
                    <input type="hidden"
                           name="configurable_bundle_product[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_selection->getId() ?>" />

                    <?php
                    $this->setProduct($_selection);
                    $attributes = $_selection->getTypeInstance()->getConfigurableAttributes($_selection);
                    ?>
                    <div class="configurable-image">
                        <a href="<?php echo $_selection->getProductUrl(); ?>" target="_blank">
                            <img src="<?php echo $block->getImage()->getImageUrl(); ?>"
                                alt="<?php echo $_selection->getName(); ?>" width="185" height="185">
                        </a>
                    </div>
                    <div class="configurable-details">
                        <a href="<?php echo $_selection->getProductUrl(); ?>" target="_blank">
                            <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection) ?>
                        </a>
                        <div class="product-sku">#<?php echo $_selection->getSku(); ?></div>
                        <?php echo $block->getChildHtml('configurable.bundle.price.final') ?>
                        <?php foreach ($attributes as $_attribute): ?>
                            <div class="field configurable required">
                                <label class="label" for="attribute<?php /* @escapeNotVerified */ echo $_attribute->getAttributeId() ?>">
                                    <span><?php echo $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
                                </label>
                                <div class="control">
                                    <select name="configurable_bundle_super_attribute[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_attribute->getAttributeId() ?>]"
                                            data-validate="{required:true}"
                                            id="attribute<?php /* @escapeNotVerified */ echo $_attribute->getAttributeId() ?>"
                                            class="super-attribute-select">
                                        <option value=""><?php /* @escapeNotVerified */ echo __('Choose an Option...') ?></option>
                                        <?php foreach ($_attribute->getOptions() as $option): ?>
                                            <option value="<?php echo $option['value_index'] ?>">
                                                <?php echo $option['store_label'] ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                    <?php
                                    echo $block->getChildBlock('default_size_chart')
                                        ->setBlockIdentifier(
                                            $_attribute->getProductAttribute()->getAttributeCode()
                                        )->toHtml();
                                    ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <?php if ($_canChangeQty): ?>
                        <div class="field qty qty-holder">
                            <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input">
                                <span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span>
                            </label>
                            <div class="control">
                                <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                                    id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                                    class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                                    type="number"
                                    name="configurable_bundle_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                                    value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                            </div>
                        </div>
                        <?php else: ?>
                            <input id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                                type="hidden"
                                name="configurable_bundle_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                                value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                        <?php endif; ?>
                        <div class="product-description">
                            <?php if($_selection->getDescription()): ?>
                                <div data-role="collapsible">
                                    <div data-role="trigger" class="title">
                                        <span>></span> Full Details
                                    </div>
                                </div>
                                <div data-role="content">
                                    <div class="content">
                                        <p>
                                            <?php echo $_selection->getDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            <?php else: ?>
                                <a href="<?php echo $_selection->getProductUrl(); ?>" target="_blank">
                                    <span>></span> Full Details
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'tabs'], function ($) {
        $(".product-description").accordion({ active: [0], multipleCollapsible: true});
    });
</script>
