<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    if($customerSession->isLoggedIn() && $customerSession->getCustomer()->getGroupId() == 2) { ?>
        <ul class="logged" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <li><a href="/high-chairs.html">High Chairs</a></li>
            <li><a href="/kids-chairs.html">Kids Chairs</a></li>
            <li><a href="/booster.html">Booster</a></li>
            <li><a href="/peanut-quick-order.html">Diaper Pad</a></li>
            <li><a href="/infant-sleeper.html">Infant Sleeper</a></li>
        </ul>
        <ul class="wholesale">
            <li><a href="/training">Training</a></li>
            <li><a href="/quick-order.html">Quick Order</a></li>
            <li><a href="/downloads.html">Downloads</a></li>
        </ul>
    <?php } else { ?>
        <ul class="unlogged" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <li><a href="/high-chairs.html">High Chairs</a></li>
            <li><a href="/kids-chairs.html">Kids Chairs</a></li>
            <li><a href="/booster.html">Booster</a></li>
            <li><a href="/peanut-quick-order.html">Diaper Pad</a></li>
            <li><a href="/infant-sleeper.html">Infant Sleeper</a></li>
        </ul>
    <?php } ?>
</nav>
