<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
        <ul style="display:none;" class="logged" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <li><a href="/high-chairs.html">High Chairs</a></li>
            <li><a href="/kids-chairs.html">Kids Chairs</a></li>
            <li><a href="/cafebooster.html">Booster</a></li>
            <li><a href="/peanut-quick-order.html">Diaper Pad</a></li>
            <li><a href="/snoozer.html">Infant Sleeper</a></li>
        </ul>
        <ul style="display:none;" class="wholesale">
            <li><a href="/training">Training</a></li>
            <li><a href="/quick-order.html">Quick Order</a></li>
            <li><a href="/downloads/">Downloads</a></li>
        </ul>
        <ul class="unlogged" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <li><a href="/high-chairs.html">High Chairs</a></li>
            <li><a href="/kids-chairs.html">Kids Chairs</a></li>
            <li><a href="/cafebooster.html">Booster</a></li>
            <li><a href="/peanut-changer.html">Diaper Pad</a></li>
            <li><a href="/snoozer.html">Infant Sleeper</a></li>
        </ul>
</nav>
<script type="text/javascript">
    require(["jquery"], function($){
        isLogin();
        function isLogin() {
            var get_url = '<?php echo $block->getBaseUrl().'/customer/ajax/islogin'?>';
            var groupArray = new Array("2", "4", "5", "6", "7", "8", "11", "14", "17");
            $.ajax({
                type: 'GET',
                url: get_url,
                dataType: 'json',
                success: function(data) {
                    if (data['login'] && groupArray.indexOf(data['group']) != -1) {
                        $('.logged').show();
                        $('.wholesale').show();
                        $('.unlogged').hide();
                    } else {
                        console.log('NOPE');
                    }
                }, error: function(xhr, ajaxOptions, thrownError) {
                    console.log(xhr.responseText);
                    console.log(thrownError);
                }
            });
        }
    });
</script>