<div class="homepage-wrapper">
    <a href="/snoozer.html" class="squeezable-wrapper">
        <img src="<?php echo $this->getViewFileUrl('images/hp-top01.jpg');?>"
             class="squeezable-bg bg01"/>
        <img src="<?php echo $this->getViewFileUrl('images/hp-top02.jpg');?>"
             class="squeezable-bg bg02"/>
        <div class="colwidth squeezable-content">
            <div class="squeezable-txt">
                <img height="192"
                     width="607"
                     src="<?php echo $this->getViewFileUrl('images/hp-top.png');?>"
                     class="squeezable-txt"
                     alt="Squeezable Comfort, Everyday Strong."/>
                <div class="squeezable-subtxt">Our cushions are durable &amp; flexible, yet soft to the touch.</div>
                <span>Learn More</span>
            </div>
        </div>
    </a>
    <div class="colwidth comfortable-wrapper">
        <a href="/comfortable-and-soft/" class="comfortable">
            <div class="comfortable-img"><img height="263"
                                              width="360"
                                              alt="Demo Video 01"
                                              src="<?php echo $this->getViewFileUrl('images/demo03.jpg');?>"/></div>
            <div class="comfortable-txt comfdiv">
                <p>Keekaroo cushions are <strong>comfortable &amp; soft</strong> and encourage posture development with
                our exclusive material.</p>
                <p><span>Learn More</span></p>
            </div>
        </a>
        <a href="/durable-and-strong/" class="durable">
            <div class="durable-img"><img height="241"
                                          width="360"
                                          alt="Demo Video 02"
                                          src="<?php echo $this->getViewFileUrl('images/demo02.jpg');?>"/></div>
            <div class="durable-txt comfdiv">
                <p>Everyday life is no match for it! <strong>Durable &amp; strong,</strong> our cushions are easy to
                care for, and clean and resistant to tears.</p>
                <p><span>Learn More</span></p>
            </div>
        </a>
    </div>
    <div class="outgrow-wrapper"
         style="background-image:url('<?php echo $this->getViewFileUrl('images/outgrow-bg.jpg');?>');">
        <a href="/height-right-high-chair-with-infant-insert.html" class="outgrow-content">
<!--            <img src="--><?php //echo $this->getViewFileUrl('images/outgrow-bg.jpg');?><!--"-->
<!--                 class="outgrow-bg"/>-->
            <div class="colwidth outgrow-txt">
                <img src="<?php echo $this->getViewFileUrl('images/outgrow-txt.png');?>"
                     height="201"
                     width="483"
                     class="outgrow-txt"
                     alt="You Can't Outgrow Keekaroo!"/>
                <div class="outgrow-subtxt">
                    <p>Our Height Right&trade; High Chair grows with children from 6 months to adults up to 250lbs.</p>
                    <span>Learn More</span>
                </div>
            </div>
        </a>
    </div>
    <div class="colwidth product-line-wrapper">
        <h2>Browse the Keekaroo Product Line</h2>
        <ul class="product-line-items">
            <li>
                <a href="/peanut-changer.html">
                    <img src="<?php echo $this->getViewFileUrl('images/productline1.jpg');?>" alt="Diaper Pad"/>
                    <h4>Diaper Pad</h4>
                    <strong>Newborn to 3 years</strong>
                    <span>Shop</span>
                </a>
            </li>
            <li>
                <a href="/snoozer.html">
                    <img src="<?php echo $this->getViewFileUrl('images/productline2.jpg');?>" alt="Infant Sleeper"/>
                    <h4>Infant Sleeper</h4>
                    <strong>Newborn to 5 months</strong>
                    <span>Shop</span>
                </a>
            </li>
            <li>
                <a href="/high-chairs.html">
                    <img src="<?php echo $this->getViewFileUrl('images/productline3.jpg');?>" alt="High Chairs"/>
                    <h4>High Chairs</h4>
                    <strong>6 months to 3 years</strong>
                    <span>Shop</span>
                </a>
            </li>
            <li>
                <a href="/cafebooster.html">
                    <img src="<?php echo $this->getViewFileUrl('images/productline4.jpg');?>" alt="Booster"/>
                    <h4>Booster</h4>
                    <strong>12 months to 4 years</strong>
                    <span>Shop</span>
                </a>
            </li>
            <li>
                <a href="/kids-chairs.html">
                    <img src="<?php echo $this->getViewFileUrl('images/productline5.jpg');?>" alt="Kids Chairs"/>
                    <h4>Kids Chairs</h4>
                    <strong>3 years and up!</strong>
                    <span>Shop</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="peaceofmind-wrapper">
        <a href="/certifications" class="peaceofmind-content"
             style="background-image:url('<?php echo $this->getViewFileUrl('images/peaceofmind-bg.jpg');?>'">
            <div class="peaceofmind-txt">
                <img src="<?php echo $this->getViewFileUrl('images/peaceofmind-txt.png');?>"
                     class="peaceofmind-img-txt"
                     alt="Peace of Mind with Keekaroo."/>
                <p>Our products are backed by our 5-Year Warranty. All Keekaroo high chair, booster, and diaper changer
                products are JPMA Certified which means they have met the strictest of performance standards.</p>
                <img src="<?php echo $this->getViewFileUrl('images/peaceofmind-jpma.png');?>"
                     class="peaceofmind-jpma"
                     alt="JPMA Certified, 5 Year Warranty"/>
            </div>
        </a>
    </div>
    <div class="bidness-wrapper">
        <h2>Find Keekaroo through these retailers!</h2>
        <a href="https://www.amazon.com/l/2594685011">
            <img src="<?php echo $this->getViewFileUrl('images/bidness-amazon.png');?>"
                 class="bidness-img bimg01"
                 target="_blank"
                 alt="Amazon"/>
        </a>
        <a href="https://www.buybuybaby.com/store/brand/keekaroo/775">
            <img src="<?php echo $this->getViewFileUrl('images/bidness-buybuybaby.png');?>"
                 class="bidness-img bimg02"
                 target="_blank"
                 alt="Buy Buy Baby"/>
        </a>
        <a href="http://www.babyearth.com/keekaroo.html?page=all">
            <img src="<?php echo $this->getViewFileUrl('images/bidness-babyearth.png');?>"
                 class="bidness-img bimg04"
                 target="_blank"
                 alt="Target"/>
        </a>
        <a href="https://mbeans.com/Keekaroo">
            <img src="<?php echo $this->getViewFileUrl('images/bidness-magicbeans.png');?>"
                 class="bidness-img bimg04"
                 target="_blank"
                 alt="Target"/>
        </a>
        <a href="https://www.target.com/bp/keekaroo">
            <img src="<?php echo $this->getViewFileUrl('images/bidness-target.png');?>"
                 class="bidness-img bimg04"
                 target="_blank"
                 alt="Target"/>
        </a>
    </div>
    <div class="colwidth magazine-wrapper">
        <div class="magazine-container owl-carousel">
            <a href="/in-the-news/" class="magazine">
                <div class="mag-img">
                    <img src="<?php echo $this->getViewFileUrl('images/magazine01.jpg');?>"
                         width="105"
                         height="136"
                         alt="Pregnancy & Newborn Magazine"/>
                </div>
                <div class="mag-txt">
                    <div class="mag-header"><p>Keekaroo Peanut Changer Featured in</p>
                        <h4>Pregnancy &amp; Newborn Magazine</h4>
                    </div>
                    <div class="mag-desc">
                        <p>"Let me count the ways I love this! You wipe it clean, unlike fabric-covered changers, so you
                        have less laundry. The cushiony surface is no-slip, so your baby doesn't slide around. And once
                        my son got wiggly, we laid it on the floor for safe diapering."</p>
                        <div class="mag-link">Read Full Review</div>
                    </div>
                </div>
            </a>
            <a href="/in-the-news/" class="magazine">
                <div class="mag-img">
                    <img src="<?php echo $this->getViewFileUrl('images/magazine02.jpg');?>"
                         width="112"
                         height="136"
                         alt="Babytalk Magazine"/>
                </div>
                <div class="mag-txt">
                    <div class="mag-header"><p>Keekaroo Peanut Changer Featured in</p>
                        <h4>Babytalk Magazine</h4>
                    </div>
                    <div class="mag-desc">
                        <p>No cover required with this cushy, wipeable changing pad.</p>
                        <div class="mag-link">Read Full Review</div>
                    </div>
                </div>
            </a>
        </div>

    </div>
</div>
<script type="text/javascript">
    require(['jquery','owlcarousel'],function($){
        $(document).ready(function(){
            $('.owl-carousel').owlCarousel({
                responsive: {
                    0: {
                        items: 1,
                        nav: true,
                        navText: ['','']
                    },
                    980: {
                        items: 2,
                        nav: false,
                        navText: ['','']
                    }
                }
            });
        });
    });
</script>