<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>

<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <label class="label">
        <span><?php echo $block->escapeHtml($_option->getTitle()); echo $block->escapeHtml($_option->getPrice()); ?></span>
    </label>
    <?php foreach ($_selections as $_selection): ?>
        <div class="pricelabel">
            <span><?php /* @escapeNotVerified */ $selPrice = $block->getSelectionPrice($_selection);
            echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($selPrice,true,false);?></span>
        </div>
    <?php endforeach;?>
    <div class="control">
        <div class="nested options-list">
            <div class="bundle-option-holder <?php if ($block->showSingle()): ?>single-bundle-option<?php endif; ?>">
                <?php if ($block->showSingle()): ?>
                    <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selections[0]) ?>
                    <input type="hidden"
                           class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                           name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"
                           value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>" />
                <?php else:?>
                    <?php if (!$_option->getRequired()): ?>
                        <div class="field choice none">
                            <input type="radio"
                                   class="radio product bundle option "
                                   id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                                   name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                                <?php echo ($_default && $_default->isSalable())?'':' checked="checked" ' ?>
                                   value=""/>
                            <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
                                <span><?php /* @escapeNotVerified */ echo __('None') ?></span>
                            </label>
                        </div>
                    <?php endif; ?>
                    <?php foreach ($_selections as $_selection): ?>
                        <div class="field choice">
                            <input type="radio"
                                   class="radio product bundle option change-container-classname"
                                   id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                                <?php if ($_option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':true}"'?>
                                   name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                                <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                                <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                                   value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"/>
                            <label class="label"
                                   for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>">
                                <span><?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection) ?></span>
                            </label>
                        </div>
                    <?php endforeach; ?>
                    <div id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></div>
                <?php endif; ?>
            </div>
            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input">
                    <span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                        id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                        class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                        type="number"
                        name="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                        data-optionId="<?php echo $_option->getId(); ?>"
                        data-optionValueId="<?php echo $_option->getSelections()[0]->getSelectionId(); ?>"
                        value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>
