<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch accordion-title"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<script type="text/javascript">
    require(["jquery"], function($){
        $('.catalog-product-view .accordion-title').click(function(e){
            e.preventDefault();
            if ($(this).parent().hasClass('soHotRightNow')) {
                $('.catalog-product-view .product.data.items > .item.title').removeClass('soHotRightNow');
            } else {
                $('.catalog-product-view .product.data.items > .item.title').removeClass('soHotRightNow');
                $(this).parent().toggleClass('soHotRightNow');
                console.log($(this).parent().offset().top);
                window.scrollTo(0, $(this).parent().offset().top);
            }
        });
        $(document).ready(function(){
            $('.accordion-title:first').parent().addClass('soHotRightNow');
        });
    });
</script>
<?php endif; ?>
